export const metadata = {
  title: "Terms of Service | Career Command Center",
  description: "Terms and conditions for using Career Command Center.",
};

export default function TermsPage() {
  return (
    <div className="bg-[#F7F9FB] min-h-screen">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-[36px] font-semibold text-primary leading-tight tracking-[-0.02em] mb-4">
          Terms of Service
        </h1>
        <p className="text-sm text-on-surface-variant mb-8">
          Last updated: August 2026
        </p>

        <div className="bg-white rounded-xl border border-outline-variant p-8 space-y-6 text-sm text-on-surface leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              Acceptance of Terms
            </h2>
            <p>
              By creating an account or using Career Command Center, you agree
              to these terms of service. If you do not agree, please do not use
              the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              Service Description
            </h2>
            <p>
              Career Command Center provides AI-powered resume tailoring, career
              history management, and job application tracking tools. The service
              uses artificial intelligence to help optimize your professional
              documents.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              Your Responsibilities
            </h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Provide accurate information about your career history</li>
              <li>Keep your account credentials secure</li>
              <li>Review all AI-generated content before submission</li>
              <li>
                Do not use the service to create misleading or fraudulent
                documents
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              AI-Generated Content
            </h2>
            <p>
              Content generated by our AI is based on the information you
              provide. You are responsible for reviewing and verifying all
              AI-generated content before using it in job applications. We do
              not guarantee specific outcomes from using our service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              Pricing and Billing
            </h2>
            <p>
              Paid plans are not live during the current beta, and we do not
              collect subscription payments. If paid access is introduced, its
              price, limits, billing period, and cancellation terms will be
              shown before you authorize a purchase.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-primary mb-3">
              Contact
            </h2>
            <p>
              For questions about these terms, use the repository&apos;s
              documented issue or security-reporting process.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
